BRDF3000: ChefDevr::OptimisationSolver< Scalar > Class Template Reference
ChefDevr::OptimisationSolver< Scalar > Class Template Reference
Class that solves the optimisation problem defined in the research paper: A Versatile Parametrisation for Measured Materials Manifold. Computes an optimised mapping from BRDFs space to a latent space.
#include <OptimisationSolver.h>
Public Member Functions
OptimisationSolver (long num_BRDFCoefficients, Scalar minStep, const Matrix< Scalar > &ZZt, unsigned int latentDim)
Constructor.
~OptimisationSolver ()=default
void optimizeMapping ()
Computes the optimized parametrisation of the BRDFs manifold. Uses Hook & Jeeves method to solve the optimisation.
const Matrix< Scalar > & getInverseMapping () const
const Vector< Scalar > & getLatentVariables () const
const Scalar & getCostValue () const
Private Member Functions
void cost (Scalar &cost, const Matrix< Scalar > &K_minus1, const Scalar &detK) const
Computes the cost of the solution defined by K_minus1.
bool exploratoryMove ()
Updates the movement vector of X that improves the solution (X_move)
bool patternMove (Vector< Scalar > &new_X, Matrix< Scalar > &new_K_minus1, Scalar &new_detK) const
Apply X_move to the latent variable vector X. Updates new_X, new_K_minus1, new_detK accordingly.
void shermanMorissonUpdate (const Matrix< Scalar > &old_K_minus1, Matrix< Scalar > &new_K_minus1, const Scalar &old_detK, Scalar &new_detK, unsigned int lv_num, Vector< Scalar > &diff_cov_vector) const
Computes the new inverse matrix K_minus1 and the new determinant of K using Sherman-Morisson formula.
void initX (const Matrix< Scalar > &K)
Initializes the latent coordinates vector X by applying the PCA method on the Z matrix and reducing its coordinates between [-1; 1].
Private Attributes
const Scalar minStep
Step below wich solution is considered optimal.
Scalar step
Value of the step for Hooke & Jeeves method.
const long nb_data
Number of BRDFs in the Z matrix.
const long num_BRDFCoefficients
Number of coefficients of each BRDF stored inside the Z matrix.
const Matrix< Scalar > ZZt
Z*Ztransposed.
unsigned int latentDim
Dimension of produced latent space.
Vector< Scalar > X
Latent variables vector.
Vector< Scalar > X_move
The movement vector of X that should improve the solution.
Matrix< Scalar > K_minus1
Inverse of K : Inverse mapping matrix.
Scalar detK
Determinant of K.
Scalar costval
Value of the cost function for this solution.
friend OptimisationTest
Static Private Attributes
static constexpr Scalar step0 = .5f
Initial value of the step.
static constexpr Scalar reduceStep = .5f
Factor of step reduction.
Detailed Description
template<typename Scalar>
class ChefDevr::OptimisationSolver< Scalar >
Class that solves the optimisation problem defined in the research paper: A Versatile Parametrisation for Measured Materials Manifold. Computes an optimised mapping from BRDFs space to a latent space.
Template Parameters
Scalar The type of scalar number to do computations with. The precision of this type is crucial to reconstruct an accurate BRDF from the latent space
Constructor & Destructor Documentation
template<typename Scalar > ChefDevr::OptimisationSolver< Scalar >::OptimisationSolver (long num_BRDFCoefficients, Scalar minStep, const Matrix< Scalar > & ZZt, unsigned int latentDim)
Constructor.
Parameters
minStep Step below which solution is considered optimal
ZZt Z * (Z transposed) where Z is the centered BRDF data matrix (BRDFs stored in row major)
latentDim Dimension of optimised latent space
References ChefDevr::OptimisationSolver< Scalar >::K_minus1, ChefDevr::OptimisationSolver< Scalar >::latentDim, ChefDevr::OptimisationSolver< Scalar >::X, ChefDevr::OptimisationSolver< Scalar >::X_move, and ChefDevr::OptimisationSolver< Scalar >::ZZt.
template<typename Scalar> ChefDevr::OptimisationSolver< Scalar >::~OptimisationSolver () default
Member Function Documentation
template<typename Scalar > void ChefDevr::OptimisationSolver< Scalar >::cost (Scalar & cost, const Matrix< Scalar > & K_minus1, const Scalar & detK) const private
Computes the cost of the solution defined by K_minus1.
Parameters
cost value of the cost to fill
K_minus1 Inverse mapping
detK Determinant of the matrix K
References ChefDevr::log(), ChefDevr::OptimisationSolver< Scalar >::num_BRDFCoefficients, and ChefDevr::OptimisationSolver< Scalar >::ZZt.
template<typename Scalar > bool ChefDevr::OptimisationSolver< Scalar >::exploratoryMove () private
Updates the movement vector of X that improves the solution (X_move)
Returns
True if has moved, false otherwise
Adds and substracts step from each element and reevaluate the cost function to check for better solutions
References ChefDevr::OptimisationSolver< Scalar >::cost(), ChefDevr::OptimisationSolver< Scalar >::costval, ChefDevr::OptimisationSolver< Scalar >::detK, ChefDevr::OptimisationSolver< Scalar >::K_minus1, ChefDevr::OptimisationSolver< Scalar >::latentDim, ChefDevr::OptimisationSolver< Scalar >::nb_data, ChefDevr::OptimisationSolver< Scalar >::shermanMorissonUpdate(), ChefDevr::OptimisationSolver< Scalar >::step, ChefDevr::OptimisationSolver< Scalar >::X, and ChefDevr::OptimisationSolver< Scalar >::X_move.
template<typename Scalar> const Scalar& ChefDevr::OptimisationSolver< Scalar >::getCostValue () const inline
Returns
A reference of the value of the cost function for the solution
References ChefDevr::OptimisationSolver< Scalar >::costval.
template<typename Scalar> const Matrix<Scalar>& ChefDevr::OptimisationSolver< Scalar >::getInverseMapping () const inline
Returns
A reference of the inverse mapping matrix
References ChefDevr::OptimisationSolver< Scalar >::K_minus1.
template<typename Scalar> const Vector<Scalar>& ChefDevr::OptimisationSolver< Scalar >::getLatentVariables () const inline
Returns
A reference of the latent variables vector
References ChefDevr::OptimisationSolver< Scalar >::X.
template<typename Scalar > void ChefDevr::OptimisationSolver< Scalar >::initX (const Matrix< Scalar > & K) private
Initializes the latent coordinates vector X by applying the PCA method on the Z matrix and reducing its coordinates between [-1; 1].
Parameters
K Variance-covariance matrix used to compute eigen vectors & values
References ChefDevr::abs(), ChefDevr::OptimisationSolver< Scalar >::latentDim, ChefDevr::OptimisationSolver< Scalar >::nb_data, and ChefDevr::OptimisationSolver< Scalar >::X.
template<typename Scalar > void ChefDevr::OptimisationSolver< Scalar >::optimizeMapping ()
Computes the optimized parametrisation of the BRDFs manifold. Uses Hook & Jeeves method to solve the optimisation.
References ChefDevr::OptimisationSolver< Scalar >::cost(), ChefDevr::OptimisationSolver< Scalar >::costval, ChefDevr::OptimisationSolver< Scalar >::detK, ChefDevr::OptimisationSolver< Scalar >::exploratoryMove(), ChefDevr::OptimisationSolver< Scalar >::initX(), ChefDevr::OptimisationSolver< Scalar >::K_minus1, ChefDevr::OptimisationSolver< Scalar >::latentDim, ChefDevr::OptimisationSolver< Scalar >::minStep, ChefDevr::OptimisationSolver< Scalar >::nb_data, ChefDevr::OptimisationSolver< Scalar >::patternMove(), ChefDevr::OptimisationSolver< Scalar >::reduceStep, ChefDevr::OptimisationSolver< Scalar >::step, ChefDevr::OptimisationSolver< Scalar >::X, and ChefDevr::OptimisationSolver< Scalar >::ZZt.
template<typename Scalar > bool ChefDevr::OptimisationSolver< Scalar >::patternMove (Vector< Scalar > & new_X, Matrix< Scalar > & new_K_minus1, Scalar & new_detK) const private
Apply X_move to the latent variable vector X. Updates new_X, new_K_minus1, new_detK accordingly.
Parameters
new_X Latent variables vector to apply the move on
new_K_minus1 New inverse mapping matrix K_minus1 to fill
new_detK New determinant of K to fill
Returns
true if effectively moved, false otherwise
References ChefDevr::OptimisationSolver< Scalar >::latentDim, ChefDevr::OptimisationSolver< Scalar >::nb_data, ChefDevr::OptimisationSolver< Scalar >::X, and ChefDevr::OptimisationSolver< Scalar >::X_move.
template<typename Scalar > void ChefDevr::OptimisationSolver< Scalar >::shermanMorissonUpdate (const Matrix< Scalar > & old_K_minus1, Matrix< Scalar > & new_K_minus1, const Scalar & old_detK, Scalar & new_detK, unsigned int lv_num, Vector< Scalar > & diff_cov_vector) const private
Computes the new inverse matrix K_minus1 and the new determinant of K using Sherman-Morisson formula.
Parameters
old_K_minus1 K_minus1 matrix before K had changed
new_K_minus1 K_minus1 matrix after K has changed (computed in this function)
old_detK Determinant of K before K had changed
new_detK Determinant of K after K has changed (computed in this function)
lv_num Number of the latent variable that has changed
diff_cov_vector The difference between the column/row of K that has changed and the column/row before it had change. Although this parameter is not const it remains unchanged when the function returns
Precondition
old_detK != 0
Computes new_K_minus_1 and new_detK from their previous values using Sherman-Morisson formula. The formula for the inverse and determinant are applied twice : one for the row modification, and another one for the column modification.
Member Data Documentation
template<typename Scalar> Scalar ChefDevr::OptimisationSolver< Scalar >::costval private
Value of the cost function for this solution.
template<typename Scalar> Scalar ChefDevr::OptimisationSolver< Scalar >::detK private
Determinant of K.
template<typename Scalar> Matrix<Scalar> ChefDevr::OptimisationSolver< Scalar >::K_minus1 private
Inverse of K : Inverse mapping matrix.
We do not store K because the algorithm doesnt require it directly : we compute only columns of K when necessary instead -> covariance vectors
template<typename Scalar> unsigned int ChefDevr::OptimisationSolver< Scalar >::latentDim private
Dimension of produced latent space.
template<typename Scalar> const Scalar ChefDevr::OptimisationSolver< Scalar >::minStep private
Step below wich solution is considered optimal.
template<typename Scalar> const long ChefDevr::OptimisationSolver< Scalar >::nb_data private
Number of BRDFs in the Z matrix.
template<typename Scalar> const long ChefDevr::OptimisationSolver< Scalar >::num_BRDFCoefficients private
Number of coefficients of each BRDF stored inside the Z matrix.
template<typename Scalar> friend ChefDevr::OptimisationSolver< Scalar >::OptimisationTest private
template<typename Scalar> constexpr Scalar ChefDevr::OptimisationSolver< Scalar >::reduceStep = .5f static private
Factor of step reduction.
template<typename Scalar> Scalar ChefDevr::OptimisationSolver< Scalar >::step private
Value of the step for Hooke & Jeeves method.
template<typename Scalar> constexpr Scalar ChefDevr::OptimisationSolver< Scalar >::step0 = .5f static private
Initial value of the step.
template<typename Scalar> Vector<Scalar> ChefDevr::OptimisationSolver< Scalar >::X private
Latent variables vector.
template<typename Scalar> Vector<Scalar> ChefDevr::OptimisationSolver< Scalar >::X_move private
The movement vector of X that should improve the solution.
template<typename Scalar> const Matrix<Scalar> ChefDevr::OptimisationSolver< Scalar >::ZZt private
Z*Ztransposed.
The documentation for this class was generated from the following files:
OptimisationSolver.h
OptimisationSolver.hpp