BRDF3000: ChefDevr::BRDFReconstructorSmallStorage< Scalar > Class Template Reference
ChefDevr::BRDFReconstructorSmallStorage< Scalar > Class Template Reference
#include <ParametrisationSmallStorage.h>
Public Member Functions
BRDFReconstructorSmallStorage (const Matrix< Scalar > &_K_minus1, const Vector< Scalar > &_X, const RowVector< Scalar > &_meanBRDF, const unsigned int _latentDim, const std::vector< std::string > &brdf_filePaths, const Scalar _mu=MU_DEFAULT, const Scalar _l=L_DEFAULT)
Constructor of the class.
~BRDFReconstructorSmallStorage ()=default
void reconstruct (RowVector< Scalar > &brdf, const Vector< Scalar > &coord) const override
Reconstructs a BRDF from its latent space coordinates.
Scalar reconstructionError (unsigned int brdfindex) const override
Computes the error between a reference brdf and this brdf reconstructed from its latent coordinates.
Public Member Functions inherited from ChefDevr::BRDFReconstructor< Scalar >
BRDFReconstructor (const Matrix< Scalar > &_K_minus1, const Vector< Scalar > &_X, const RowVector< Scalar > &_meanBRDF, const unsigned int _latentDim, const Scalar _mu=MU_DEFAULT, const Scalar _l=L_DEFAULT)
Constructor of the class.
virtual ~BRDFReconstructor ()=default
unsigned int getLatentDim () const
long getBRDFCoeffNb () const
Private Attributes
const Matrix< Scalar > & _K_minus1
Inverse of K : Inverse mapping matrix.
const std::vector< std::string > & brdf_filePaths
the list of BRDF filePaths in the order in which they were read
Additional Inherited Members
Protected Attributes inherited from ChefDevr::BRDFReconstructor< Scalar >
const Vector< Scalar > & X
Latent variables vector.
const RowVector< Scalar > & meanBRDF
Mean column of Z (before it was centered)
const unsigned int latentDim
Dimension of the latent space.
const long nb_data
Number of BRDFs in Z.
const Scalar mu
Value of the mu constant that helps interpolation source data.
const Scalar l
l constant used in covariance function
Constructor & Destructor Documentation
template<typename Scalar> ChefDevr::BRDFReconstructorSmallStorage< Scalar >::BRDFReconstructorSmallStorage (const Matrix< Scalar > & _K_minus1, const Vector< Scalar > & _X, const RowVector< Scalar > & _meanBRDF, const unsigned int _latentDim, const std::vector< std::string > & brdf_filePaths, const Scalar _mu = MU_DEFAULT, const Scalar _l = L_DEFAULT) inline
Constructor of the class.
Parameters
_K_minus1 Inverse mapping matrix
_X Latent variables vector
_meanBRDF The mean BRDF (mean of the rows of Z before it was centered)
_latentDim Dimension of the latent space
reader The reader of BRDFs
_mu Value of the mu constant that helps interpolation source data
_l Constant defined in the research paper
References ChefDevr::BRDFReconstructorSmallStorage< Scalar >::brdf_filePaths, ChefDevr::BRDFReconstructorSmallStorage< Scalar >::reconstruct(), ChefDevr::BRDFReconstructorSmallStorage< Scalar >::reconstructionError(), and ChefDevr::BRDFReconstructorSmallStorage< Scalar >::~BRDFReconstructorSmallStorage().
template<typename Scalar> ChefDevr::BRDFReconstructorSmallStorage< Scalar >::~BRDFReconstructorSmallStorage () default
Member Function Documentation
template<typename Scalar > void ChefDevr::BRDFReconstructorSmallStorage< Scalar >::reconstruct (RowVector< Scalar > & brdf, const Vector< Scalar > & coord) const override virtual
Reconstructs a BRDF from its latent space coordinates.
Parameters
[out] brdf The brdf data vector to fill
[in] coord Coordinates of the latent space point from which a BRDF is reconstructed
Returns
The BRDF data as a row vector
Implements ChefDevr::BRDFReconstructor< Scalar >.
template<typename Scalar > Scalar ChefDevr::BRDFReconstructorSmallStorage< Scalar >::reconstructionError (unsigned int brdfindex) const override virtual
Computes the error between a reference brdf and this brdf reconstructed from its latent coordinates.
Parameters
brdfindex : The index of the brdf in the list of brdfs read to construct Z
Returns
the mean square error between a reference brdf and its reconstruction
Implements ChefDevr::BRDFReconstructor< Scalar >.
Member Data Documentation
template<typename Scalar> const Matrix<Scalar>& ChefDevr::BRDFReconstructorSmallStorage< Scalar >::_K_minus1 private
Inverse of K : Inverse mapping matrix.
template<typename Scalar> const std::vector<std::string>& ChefDevr::BRDFReconstructorSmallStorage< Scalar >::brdf_filePaths private
the list of BRDF filePaths in the order in which they were read
The documentation for this class was generated from the following files:
ParametrisationSmallStorage.h
ParametrisationSmallStorage.hpp