BRDF3000: ChefDevr::BRDFReconstructorWithZ< Scalar > Class Template Reference
ChefDevr::BRDFReconstructorWithZ< Scalar > Class Template Reference
#include <ParametrisationWithZ.h>
Public Member Functions
BRDFReconstructorWithZ (const Matrix< Scalar > &_Zcentered, const Matrix< Scalar > &_K_minus1, const Vector< Scalar > &_X, const RowVector< Scalar > &_meanBRDF, const unsigned int _latentDim, const Scalar _mu=MU_DEFAULT, const Scalar _l=L_DEFAULT)
Constructor of the class.
~BRDFReconstructorWithZ ()=default
void reconstruct (RowVector< Scalar > &brdf, const Vector< Scalar > &coord) const override
Reconstructs a BRDF from its latent space coordinates.
Scalar reconstructionError (unsigned int brdfindex) const override
Computes the error between a reference brdf and this brdf reconstructed from its latent coordinates.
Public Member Functions inherited from ChefDevr::BRDFReconstructor< Scalar >
BRDFReconstructor (const Matrix< Scalar > &_K_minus1, const Vector< Scalar > &_X, const RowVector< Scalar > &_meanBRDF, const unsigned int _latentDim, const Scalar _mu=MU_DEFAULT, const Scalar _l=L_DEFAULT)
Constructor of the class.
virtual ~BRDFReconstructor ()=default
unsigned int getLatentDim () const
long getBRDFCoeffNb () const
Private Member Functions
void reconstructWithoutMean (RowVector< Scalar > &brdf, const Vector< Scalar > &coord) const
Reconstructs a BRDF for latent space coordinates without adding the mean.
Private Attributes
const Matrix< Scalar > & Zcentered
Centered BRDFs data matrix (BRDFs stored in row major)
const Matrix< Scalar > Km1Zc
K_minus1 times Z centered.
Additional Inherited Members
Protected Attributes inherited from ChefDevr::BRDFReconstructor< Scalar >
const Vector< Scalar > & X
Latent variables vector.
const RowVector< Scalar > & meanBRDF
Mean column of Z (before it was centered)
const unsigned int latentDim
Dimension of the latent space.
const long nb_data
Number of BRDFs in Z.
const Scalar mu
Value of the mu constant that helps interpolation source data.
const Scalar l
l constant used in covariance function
Constructor & Destructor Documentation
template<typename Scalar> ChefDevr::BRDFReconstructorWithZ< Scalar >::BRDFReconstructorWithZ (const Matrix< Scalar > & _Zcentered, const Matrix< Scalar > & _K_minus1, const Vector< Scalar > & _X, const RowVector< Scalar > & _meanBRDF, const unsigned int _latentDim, const Scalar _mu = MU_DEFAULT, const Scalar _l = L_DEFAULT) inline
Constructor of the class.
Parameters
_Zcentered Centered BRDFs data matrix (BRDFs stored in row major),
_K_minus1 Inverse mapping matrix
_X Latent variables vector
_meanBRDF The mean BRDF (mean of the rows of Z before it was centered)
_latentDim Dimension of the latent space
_mu Value of the mu constant that helps interpolation source data
_l Constant defined in the research paper
References ChefDevr::BRDFReconstructorWithZ< Scalar >::reconstruct(), ChefDevr::BRDFReconstructorWithZ< Scalar >::reconstructionError(), and ChefDevr::BRDFReconstructorWithZ< Scalar >::~BRDFReconstructorWithZ().
template<typename Scalar> ChefDevr::BRDFReconstructorWithZ< Scalar >::~BRDFReconstructorWithZ () default
Member Function Documentation
template<typename Scalar > void ChefDevr::BRDFReconstructorWithZ< Scalar >::reconstruct (RowVector< Scalar > & brdf, const Vector< Scalar > & coord) const override virtual
Reconstructs a BRDF from its latent space coordinates.
Parameters
brdf The brdf data vector to fill
coord Coordinates of the latent space point to recontruct as a BRDF
Returns
The BRDF data as a row vector
Implements ChefDevr::BRDFReconstructor< Scalar >.
template<typename Scalar > Scalar ChefDevr::BRDFReconstructorWithZ< Scalar >::reconstructionError (unsigned int brdfindex) const override virtual
Computes the error between a reference brdf and this brdf reconstructed from its latent coordinates.
Parameters
brdfindex : The index of the brdf in the list of brdfs read to construct Z
Returns
the mean square error between a reference brdf and its reconstruction
Implements ChefDevr::BRDFReconstructor< Scalar >.
template<typename Scalar > void ChefDevr::BRDFReconstructorWithZ< Scalar >::reconstructWithoutMean (RowVector< Scalar > & brdf, const Vector< Scalar > & coord) const private
Reconstructs a BRDF for latent space coordinates without adding the mean.
Parameters
brdf The brdf data vector to fill
coord Coordinates of the latent space point to recontruct as a BRDF
Returns
The BRDF data as a column vector
Member Data Documentation
template<typename Scalar> const Matrix<Scalar> ChefDevr::BRDFReconstructorWithZ< Scalar >::Km1Zc private
K_minus1 times Z centered.
template<typename Scalar> const Matrix<Scalar>& ChefDevr::BRDFReconstructorWithZ< Scalar >::Zcentered private
Centered BRDFs data matrix (BRDFs stored in row major)
The documentation for this class was generated from the following files:
ParametrisationWithZ.h
ParametrisationWithZ.hpp