BRDF3000: ChefDevr::BRDFReader Class Reference
ChefDevr::BRDFReader Class Reference
This class is used to read all the BRDF references and to sample them.
#include <BRDFReader.h>
Classes
class BRDFReaderError
Public Member Functions
BRDFReader ()
~BRDFReader ()
template<typename Scalar >
Matrix< Scalar > createZ (const char *fileDirectory)
Read all the BRDFs stored in a given directory.
template<typename Scalar >
ResampledBRDF resampleBRDF (const Vector< Scalar > &brdf, unsigned int num_sampling)
Resamples a BRDF.
const std::vector< std::string > & getBRDFFilenames () const
Private Member Functions
template<typename Scalar >
Vector< Scalar > read_brdf (const char *filePath)
Read a BRDF from a file.
template<typename Scalar >
void lookup_brdf_val (const Vector< Scalar > &brdf, double theta_in, double phi_in, double theta_out, double phi_out, double &red_value, double &green_value, double &blue_value)
Extracts a color in a BRDF from a pair of incoming and outgoing angles.
void std_coords_to_half_diff_coords (double theta_in, double phi_in, double theta_out, double phi_out, double &theta_half, double &phi_half, double &theta_diff, double &phi_diff)
Converts standard coordinates to half vector/difference vector coordinates.
Eigen::Vector3d rotate_vector (const Eigen::Vector3d &vector, const Eigen::Vector3d &axis, double angle)
Rotates a vector along an axis.
Eigen::Vector3d compute_direction (double theta, double phi)
Computes a direction from angles.
unsigned int theta_half_index (double theta_half)
Lookup theta_half index.
unsigned int theta_diff_index (double theta_diff)
Lookup theta_diff index.
unsigned int phi_diff_index (double phi_diff)
Lookup phi_diff index.
Private Attributes
std::vector< std::string > brdf_filenames
the list of BRDF paths in the order in which they were read
Static Private Attributes
static const unsigned int samplingResolution_thetaH = 90
static const unsigned int samplingResolution_thetaD = 90
static const unsigned int samplingResolution_phiD = 360
static constexpr double red_scale = 1.0 / 1500.0
static constexpr double green_scale = 1.15 / 1500.0
static constexpr double blue_scale = 1.66 / 1500.0
Detailed Description
This class is used to read all the BRDF references and to sample them.
Constructor & Destructor Documentation
BRDFReader()
ChefDevr::BRDFReader::BRDFReader ()
~BRDFReader()
ChefDevr::BRDFReader::~BRDFReader () inline
Member Function Documentation
compute_direction()
Vector3d ChefDevr::BRDFReader::compute_direction (double theta, double phi) private
Computes a direction from angles.
Parameters
theta the theta angle
phi the phi angle
Returns
the direction
createZ()
template<typename Scalar > Matrix< Scalar > ChefDevr::BRDFReader::createZ (const char * fileDirectory)
Read all the BRDFs stored in a given directory.
Parameters
fileDirectory the path of the directory where all the brdfs are stored
Returns
Z BRDFs data matrix where each column represents a BRDF
Initializes the list of BRDFs paths in the order in which they were read.
As the set of BRDFs can be heavy, we use the stxxl library Thus, a problem is not likely to occur if the RAM is too small compared to the set of BRDFs Indeed, in this case, the set of BRDFs is stored inside the disk
getBRDFFilenames()
const std::vector<std::string>& ChefDevr::BRDFReader::getBRDFFilenames () const inline
Returns
the list of BRDF paths in the order in which they were read
lookup_brdf_val()
template<typename Scalar > void ChefDevr::BRDFReader::lookup_brdf_val (const Vector< Scalar > & brdf, double theta_in, double phi_in, double theta_out, double phi_out, double & red_value, double & green_value, double & blue_value) private
Extracts a color in a BRDF from a pair of incoming and outgoing angles.
Parameters
[in] brdf the BRDF from which the color is extracted
[in] theta_in incoming angle of theta
[in] phi_in incoming angle of phi
[in] theta_out outgoing angle of theta
[in] phi_out outgoing angle of phi
[out] red_value red channel of the extracted color
[out] green_value green channel of the extracted color
[out] blue_value blue channel of the extracted color
References blue_scale, green_scale, phi_diff_index(), red_scale, samplingResolution_phiD, samplingResolution_thetaD, samplingResolution_thetaH, std_coords_to_half_diff_coords(), theta_diff_index(), and theta_half_index().
phi_diff_index()
unsigned int ChefDevr::BRDFReader::phi_diff_index (double phi_diff) private
Lookup phi_diff index.
Parameters
phi_diff the angle corresponding to the index
Returns
the index
Precondition
phi_diff is between 0 and pi
Postcondition
the result is between 0 and 179
read_brdf()
template<typename Scalar > Vector< Scalar > ChefDevr::BRDFReader::read_brdf (const char * filePath) private
Read a BRDF from a file.
Parameters
filePath the path of the BRDF's file
Returns
All the coefficients of a BRDF as a vector of scalars
If the file is not found, returns an error
As the set of BRDFs can be heavy, we use the stxxl library Thus, a problem is not likely to occur if the RAM is too small compared to the set of BRDFs Indeed, in this case, the set of BRDFs is stored inside the disk
References samplingResolution_phiD, samplingResolution_thetaD, and samplingResolution_thetaH.
resampleBRDF()
template<typename Scalar > ResampledBRDF ChefDevr::BRDFReader::resampleBRDF (const Vector< Scalar > & brdf, unsigned int num_sampling)
Resamples a BRDF.
Parameters
brdf the BRDF to be sampled
num_sampling the number of possible values for the angles that parametrizes the retained BRDF values
References ChefDevr::ResampledBRDF::data, lookup_brdf_val(), ChefDevr::ResampledBRDF::phiNum, ChefDevr::ResampledBRDF::phiStep, ChefDevr::ResampledBRDF::thetaNum, and ChefDevr::ResampledBRDF::thetaStep.
rotate_vector()
Vector3d ChefDevr::BRDFReader::rotate_vector (const Eigen::Vector3d & vector, const Eigen::Vector3d & axis, double angle) private
Rotates a vector along an axis.
Parameters
vector the vector to be rotated
axis the axis along which the vector is rotated
angle the angle of the rotation
Returns
the rotated vector
std_coords_to_half_diff_coords()
void ChefDevr::BRDFReader::std_coords_to_half_diff_coords (double theta_in, double phi_in, double theta_out, double phi_out, double & theta_half, double & phi_half, double & theta_diff, double & phi_diff) private
Converts standard coordinates to half vector/difference vector coordinates.
Parameters
[in] theta_in incoming angle of theta
[in] phi_in incoming angle of phi
[in] theta_out outgoing angle of theta
[in] phi_out outgoing angle of phi
[out] theta_half theta in half vector coordinates
[out] phi_half phi in half vector coordinates
[out] theta_diff theta in difference vector coordinates
[out] phi_diff phi in difference vector coordinates
References compute_direction(), and rotate_vector().
theta_diff_index()
unsigned int ChefDevr::BRDFReader::theta_diff_index (double theta_diff) private
Lookup theta_diff index.
Parameters
theta_diff the angle corresponding to the index
Returns
the index
Precondition
theta_diff is between 0 and PI / 2
Postcondition
the result is between 0 and 89
theta_half_index()
unsigned int ChefDevr::BRDFReader::theta_half_index (double theta_half) private
Lookup theta_half index.
Parameters
theta_half the angle corresponding to the index
Returns
the index
Precondition
theta_half is between 0 and PI / 2
Postcondition
the result is between 0 and 89
This is a non-linear mapping!
References samplingResolution_thetaH.
Member Data Documentation
blue_scale
constexpr double ChefDevr::BRDFReader::blue_scale = 1.66 / 1500.0 static private
brdf_filenames
std::vector<std::string> ChefDevr::BRDFReader::brdf_filenames private
the list of BRDF paths in the order in which they were read
green_scale
constexpr double ChefDevr::BRDFReader::green_scale = 1.15 / 1500.0 static private
red_scale
constexpr double ChefDevr::BRDFReader::red_scale = 1.0 / 1500.0 static private
samplingResolution_phiD
const unsigned int ChefDevr::BRDFReader::samplingResolution_phiD = 360 static private
samplingResolution_thetaD
const unsigned int ChefDevr::BRDFReader::samplingResolution_thetaD = 90 static private
samplingResolution_thetaH
const unsigned int ChefDevr::BRDFReader::samplingResolution_thetaH = 90 static private
The documentation for this class was generated from the following files:
BRDFReader.h
BRDFReader.cpp
BRDFReader.hpp