BRDF3000: main.cpp File Reference
main.cpp File Reference
#include <chrono>
#include <cstdio>
#include "Parametrisation/types.h"
#include "Parametrisation/ParametrisationWithZ.h"
#include "Parametrisation/ParametrisationSmallStorage.h"
#include "BRDFReader/BRDFReader.h"
#include "Optimisation/OptimisationSolver.h"
#include "Optimisation/OptiDataWriter.h"
#include "Optimisation/Albedo.h"
Macros
#define WRONG_USAGE 1
Typedefs
using Scalar = long double
Functions
template<typename Scalar >
void writeBRDF (const std::string &path, const RowVector< Scalar > &brdf)
static void show_usage (const char *name_program)
bool is_number (const std::string &s)
int main (int argc, const char *argv[])
Macro Definition Documentation
#define WRONG_USAGE 1
Typedef Documentation
using Scalar = long double
Function Documentation
bool is_number (const std::string & s)
int main (int argc, const char * argv[])
References ChefDevr::centerMat(), ChefDevr::BRDFReader::createZ(), ChefDevr::BRDFReader::createZZt_centered(), ChefDevr::BRDFReconstructor< Scalar >::getBRDFCoeffNb(), ChefDevr::BRDFReader::getBRDFFilenames(), ChefDevr::BRDFReader::getBRDFFilePaths(), ChefDevr::OptimisationSolver< Scalar >::getInverseMapping(), ChefDevr::OptimisationSolver< Scalar >::getLatentVariables(), is_number(), ChefDevr::OptimisationSolver< Scalar >::optimizeMapping(), ChefDevr::BRDFReconstructor< Scalar >::reconstruct(), ChefDevr::BRDFReconstructor< Scalar >::reconstructionError(), show_usage(), and WRONG_USAGE.
static void show_usage (const char * name_program) static
template<typename Scalar > void writeBRDF (const std::string & path, const RowVector< Scalar > & brdf)
References ChefDevr::MERLReader::samplingResolution_phiD, ChefDevr::MERLReader::samplingResolution_thetaD, and ChefDevr::MERLReader::samplingResolution_thetaH.