BRDF3000: ChefDevr Namespace Reference
ChefDevr Namespace Reference
Albedo.hpp.
Classes
class Albedo
Provides albedo computation using the most efficient parallelization solution made available by the material.
class BRDFReader
This class is used to read all the BRDF references and to sample them.
class BRDFReconstructor
Class that allows BRDF reconstruction from latent space coordinates.
class OptimisationSolver
Class that solves the optimisation problem defined in the research paper: A Versatile Parametrisation for Measured Materials Manifold. Computes an optimised mapping from BRDFs space to a latent space.
Typedefs
using float128 = boost::multiprecision::float128
template<typename Scalar >
using Matrix = Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic >
template<typename Scalar >
using Vector = Eigen::Matrix< Scalar, Eigen::Dynamic, 1 >
template<typename Scalar >
using RowVector = Eigen::Matrix< Scalar, 1, Eigen::Dynamic >
Functions
template<typename Scalar >
Scalar exp (Scalar x)
template<>
float128 exp< float128 > (float128 x)
template<typename Scalar >
Scalar log (Scalar x)
template<>
float128 log< float128 > (float128 x)
template<typename Scalar >
Scalar abs (Scalar x)
template<>
float128 abs< float128 > (float128 x)
template<typename Scalar >
Scalar covariance (const Vector< Scalar > &x1, const Vector< Scalar > &x2, const Scalar mu=MU_DEFAULT, const Scalar l=L_DEFAULT)
Covariance function given in the research paper : A Versatile Parametrization for Measured Materials Manifold.
template<typename Scalar >
void centerMat (Matrix< Scalar > &Z, RowVector< Scalar > &meanBRDF)
Centers matrix by sustracting mean to all columns.
template<typename Scalar >
void computeCovVector (Scalar *cov_vector, const Vector< Scalar > &X, const Vector< Scalar > &coordRef, unsigned int dim, unsigned int nb_data)
Computes the covariance column vector for the coordRef coordinates variable.
template<typename Scalar >
void writeAlbedoMap (const std::string &path, const Matrix< Scalar > &Z, const Vector< Scalar > &X, const Matrix< Scalar > &K_minus1, const RowVector< Scalar > &meanBRDF, const unsigned int latentDim, const unsigned int albedoSampling=4, const unsigned int width=16, const unsigned int height=16, const double latentWidth=3., const double latentHeight=3)
Writes the image of the latent space on the disk.
template<typename Scalar >
void writeAlbedoMap (const std::string &path, const BRDFReconstructor< Scalar > &reconstructor, const unsigned int albedoSampling=4, const unsigned int width=16, const unsigned int height=16, const double latentWidth=3., const double latentHeight=3)
Writes the image of the latent space on the disk.
template<typename Scalar >
void writeParametrisationData (const std::string &path, const std::vector< std::string > &brdfsFilenames, const Vector< Scalar > &X, const Matrix< Scalar > &K_minus1, const unsigned int latentDim)
Writes the data that defines the parametrisation (without Z)
void progressBar (double progress)
Detailed Description
Albedo.hpp.
Typedef Documentation
float128
using ChefDevr::float128 = typedef boost::multiprecision::float128
Matrix
template<typename Scalar > using ChefDevr::Matrix = typedef Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic>
Template Parameters
Scalar Type used for the scalar numbers stored
RowVector
template<typename Scalar > using ChefDevr::RowVector = typedef Eigen::Matrix<Scalar, 1, Eigen::Dynamic>
Template Parameters
Scalar Type used for the scalar numbers stored
Vector
template<typename Scalar > using ChefDevr::Vector = typedef Eigen::Matrix<Scalar, Eigen::Dynamic, 1>
Template Parameters
Scalar Type used for the scalar numbers stored
Function Documentation
abs()
template<typename Scalar > Scalar ChefDevr::abs (Scalar x) inline
abs< float128 >()
template<> float128 ChefDevr::abs< float128 > (float128 x) inline
References abs().
centerMat()
template<typename Scalar > void ChefDevr::centerMat (Matrix< Scalar > & Z, RowVector< Scalar > & meanBRDF)
Centers matrix by sustracting mean to all columns.
Parameters
Z Matrix to center
meanBRDF Mean column of Z (filled in the function) Z should be in column major
computeCovVector()
template<typename Scalar > void ChefDevr::computeCovVector (Scalar * cov_vector, const Vector< Scalar > & X, const Vector< Scalar > & coordRef, unsigned int dim, unsigned int nb_data)
Computes the covariance column vector for the coordRef coordinates variable.
Parameters
cov_vector The covariance column vector to fill
X_reshaped Latent variables matrix in the form such that each column is a latent variable with a number of rows equal to dim.
coordRef Coordinates to compare with every latent variable
dim Dimension of latent space
nb_data Number of data
Returns
Covariance column vector
Covariance is computed with the "covariance" function
covariance()
template<typename Scalar > Scalar ChefDevr::covariance (const Vector< Scalar > & x1, const Vector< Scalar > & x2, const Scalar mu = MU_DEFAULT, const Scalar l = L_DEFAULT) inline
Covariance function given in the research paper : A Versatile Parametrization for Measured Materials Manifold.
Parameters
x1 First latent variable
x2 Second latent variable
mu The constant that helps interpolating data while keeping good solution
l Constant defined in the research paper
Returns
Covariance value
References exp().
exp()
template<typename Scalar > Scalar ChefDevr::exp (Scalar x) inline
exp< float128 >()
template<> float128 ChefDevr::exp< float128 > (float128 x) inline
References exp().
log()
template<typename Scalar > Scalar ChefDevr::log (Scalar x) inline
log< float128 >()
template<> float128 ChefDevr::log< float128 > (float128 x) inline
References log().
progressBar()
void ChefDevr::progressBar (double progress)
writeAlbedoMap() [1/2]
template<typename Scalar > void ChefDevr::writeAlbedoMap (const std::string & path, const Matrix< Scalar > & Z, const Vector< Scalar > & X, const Matrix< Scalar > & K_minus1, const RowVector< Scalar > & meanBRDF, const unsigned int latentDim, const unsigned int albedoSampling = 4, const unsigned int width = 16, const unsigned int height = 16, const double latentWidth = 3., const double latentHeight = 3)
Writes the image of the latent space on the disk.
Parameters
path Path of the folder to write into
Z Centered BRDF data matrix (BRDFs stored in row major)
X Latent variables vector
K_minus1 Inverse mapping matrix
meanBRDF Mean column of Z (before it was centered)
albedoSampling Sampling resolution in phi for albedo computation
width Width of the image in number of pixels
height Height of the image in number of pixels
latentWidth Width of the plotted latent space (centered on 0)
latentHeight Height of the plotted latent space (centered on 0)
writeAlbedoMap() [2/2]
template<typename Scalar > void ChefDevr::writeAlbedoMap (const std::string & path, const BRDFReconstructor< Scalar > & reconstructor, const unsigned int albedoSampling = 4, const unsigned int width = 16, const unsigned int height = 16, const double latentWidth = 3., const double latentHeight = 3)
Writes the image of the latent space on the disk.
Parameters
path Path of the folder to write into
reconstructor Reconstructor object used to reconstruct BRDFs from coordinates
albedoSampling Sampling resolution in phi for albedo computation
width Width of the image in number of pixels
height Height of the image in number of pixels
latentWidth Width of the plotted latent space (centered on 0)
latentHeight Height of the plotted latent space (centered on 0)
References ChefDevr::BRDFReconstructor< Scalar >::getBRDFCoeffNb(), ChefDevr::BRDFReconstructor< Scalar >::getLatentDim(), progressBar(), and ChefDevr::BRDFReconstructor< Scalar >::reconstruct().
writeParametrisationData()
template<typename Scalar > void ChefDevr::writeParametrisationData (const std::string & path, const std::vector< std::string > & brdfsFilenames, const Vector< Scalar > & X, const Matrix< Scalar > & K_minus1, const unsigned int latentDim)
Writes the data that defines the parametrisation (without Z)
Parameters
path Path of the folder to write in
brdfsFilenames List of the BRDF files used for the parametrization in the right order (consistent with Z matrix)
X Latent variables vector
K_minus1 Inverse mapping matrix
latentDim Dimension of latent space
File format
filename = paramtrzdata
propriete intellectuelle et commentaires
scalar_type
"inverse mapping matrix"
nb_rows nb_cols
K_minus1
"latent variables"
number_of_latent_variables
latent_space_dimension
brdf_filename x11 x12 ... x1d
brdf_filename x21 x22 ... x1d
...
brdf_filename xn1 xn2 ... xnd